"'Configuration Screen' As screen":
    Fill: =Color.White

    lbconfig_editexpense_defaultcolumntext As label:
        Height: =36
        Size: =21
        Text: ="Enter details"
        Width: =560
        Y: =6
        ZIndex: =1

    lbconfig_expenseline_name As label:
        Height: =43
        Size: =21
        Text: ="TrvExpTrans"
        Width: =560
        Y: =42
        ZIndex: =2

    lbconfig_expensereport_name As label:
        Height: =43
        Size: =21
        Text: ="expensereport"
        Width: =560
        Y: =85
        ZIndex: =3

    lbconfig_resolution_factor As label:
        Height: =43
        Size: =21
        Text: =Value("1.71","en-US")
        Width: =560
        Y: =128
        ZIndex: =4

    icongconfig_backbutton As icon.ChevronLeft:
        Color: =RGBA(110, 110, 110, 1)
        Height: =44
        Icon: =Icon.ChevronLeft
        Width: =28
        X: =12
        Y: =171
        ZIndex: =5

    scr00_drp_LanguageSelection As dropdown:
        Height: =74
        Items: =["en-US","pt-br"]
        OnChange: =
        Size: =21
        Width: =278
        X: =300
        Y: =97
        ZIndex: =9

    lbconfig_LegalEntity As label:
        Height: =43
        Size: =21
        Text: =
        Width: =560
        Y: =215
        ZIndex: =16

    lbconfig_APIVersion As label:
        Height: =43
        Size: =21
        Text: ="1.0"
        Width: =560
        Y: =272
        ZIndex: =17

    lbconfig_TenantId As label:
        Height: =43
        Size: =21
        Text: ="72f988bf-86f1-41af-91ab-2d7cd011db47"
        Width: =560
        Y: =337
        ZIndex: =18

    lbconfig_EnvironmentId As label:
        Height: =43
        Size: =21
        Text: ="9ef5e773-0e5d-4235-8727-edc90f182948"
        Width: =560
        Y: =398
        ZIndex: =19

    cmp_footer_rct_Seprator_2 As rectangle:
        Fill: =RGBA(200, 200, 200, 1)
        Height: =0.85
        Width: =640
        Y: =20
        ZIndex: =22

    navigateIcon As icon.ChevronRight:
        Color: =RGBA(110, 110, 110, 1)
        Height: =30
        HoverColor: =Self.Color
        Icon: =Icon.ChevronRight
        PressedColor: =Self.Color
        Width: =30
        X: =40
        Y: =40
        ZIndex: =24

